### PR TITLE
[FIX]: add helper utils

### PR DESCRIPTION
**Pull request by tpegl**
Addresses #4 by moving output functions and variables to `utils.py` and importing from it in modules.

- Create some new functions using the colorama variables to make output more consistent and easier to use
- Move some imports around based on pylint recommendation

This PR moves a lot and touches almost every file so there's no rush on checking it. Please take as long as you need and if it's too much (or just not how you'd like it done), please let me know :pray: thanks for letting me contribute more!

### CODE REVIEW

**Comment by 6abd** [comment]
Sorry for the late response, will check it out this weekend!

**Comment by 6abd** [comment]
Everything seems good, but I get the following warning after running a command:

`/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '`

Does this only happen on my machine?

**Comment by tpegl** [comment]
What OS and what command?

I don't see it when I run `ovpn` and `config` but I'm on EndeavourOS. I'll check on Windows too and see if I can get some MacOS to try on

**Comment by 6abd** [comment]
MacOS, apicon and falcon when I tested them, but I think it's on every command for me.

**Comment by 6abd** [comment]
I honestly couldn't tell you, but that seems to have been the issue. Could you update your changes for that fix? I can merge it once that's done. Thanks!

**Comment by tpegl** [comment]
Absolutely, I'll update it now!

**Pull request merged**
